lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase: 'test'
    token_ttl:        3600


gesdinet_jwt_refresh_token:
    ttl: 2592000
    ttl_update: true
    firewall: api

